const customerData = [
  {
    id:1,
    name:'Dipesh',
    email:'dipesh@sfbank.me',
    balance:20650,
  },
  {
    id:2,
    name:'Vibhor',
    email:'vibhor@sfbank.me',
    balance:50600,
  },
  {
    id:3,
    name:'Shyam',
    email:'shyam@sfbank.me',
    balance:20000,
  },
  {
    id:4,
    name:'Dikshit',
    email:'dikshit@sfbank.me',
    balance:10300,
  },
  {
    id:5,
    name:'Parimal',
    email:'parimal@sfbank.me',
    balance:23900,
  },
  {
    id:6,
    name:'Akash',
    email:'akash@sfbank.me',
    balance:12000,
  },
  {
    id:7,
    name:'James',
    email:'james@sfbank.me',
    balance:45000,
  },
  {
    id:8,
    name:'Vishes',
    email:'vishes@sfbank.me',
    balance:78900,
  },
  {
    id:9,
    name:'Tara',
    email:'tara@sfbank.me',
    balance:90200,
  },
  {
    id:10,
    name:'Shruti',
    email:'shruti@sfbank.me',
    balance:123000,
  },
]

export default customerData